apiVersion: v1
kind: Secret
metadata:
  name: amp-portops-secrets
  namespace: amp-portops
type: Opaque
stringData:
  DATABASE_URL: "${PANAMA_DB_URL}"
  AMP_API_SECRET_KEY: "${AMP_SECRET_KEY}"
  AIS_SATELLITE_API_TOKEN: "${AIS_API_TOKEN}"
