apiVersion: v1
kind: Secret
metadata:
  name: amp-portops-secrets
  namespace: amp-portops
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:secure_panama_pass@timescaledb-service:5432/amp_portops"
  AMP_API_SECRET_KEY: "panama-amp-mlops-token-2026-production"
  AIS_SATELLITE_API_TOKEN: "spire-maritime-satellite-token-demo"
